name: mir-kiosk-kodi
adopt-info: kodi
summary: Kodi packaged as a mir-kiosk snap
description: Kodi-wayland packaged as a mir-kiosk snap
confinement: strict
grade: devel
base: core18

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  # Prep PulseAudio
  PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

layout:
  /usr/share:
    bind: $SNAP/usr/share

plugs:
  wayland:
  opengl:
  pulseaudio:
  alsa:
  avahi-observe:
  hardware-observe:
  locale-control:
  mount-observe:
  network-observe:
  removable-media:
  shutdown:
  system-observe:

apps:
  kodi:
    command: bin/kodi-launch.sh
    daemon: simple
    restart-condition: on-failure

  mir-kiosk-kodi:
    command: bin/kodi-launch.sh
    desktop: usr/share/applications/kodi.desktop

parts:
  glue:
    plugin: dump
    source: glue

  kodi:
    override-pull: |
      snapcraftctl pull
      kodi_version=`LANG=C apt-cache policy kodi-wayland | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      snapcraftctl set-version $kodi_version
    plugin: ppa
    ppa: team-xbmc/ppa
    override-stage: |
      sed --in-place s'!/usr!${SNAP}/usr!' $SNAPCRAFT_PART_INSTALL/usr/bin/kodi
      snapcraftctl stage
    stage-packages:
      - kodi-wayland
      - kodi-repository-kodi
      - kodi-visualization-spectrum
      - samba-libs
      - libfstrcmp0
      - libpulse0

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
